name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.13.0
        with:
          otp-version: "23.2"
          gleam-version: "0.23.0-rc2"

      # Check formatting
      - run: gleam format --check backend/src backend/test

      # Install dependencies
      - run: cd backend && gleam deps download
      - run: cd frontend && gleam deps download && npm ci

      # Run tests
      - run: cd frontend && gleam test
      - run: cd backend && gleam test
